//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluggedMVC.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmployeePersonTemporalInfo
    {
        public int BusinessEntityID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string JobTitle { get; set; }
        public string MaritalStatus { get; set; }
        public string Gender { get; set; }
        public short VacationHours { get; set; }
        public short SickLeaveHours { get; set; }
    }
}
