#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using PluggedMVC.WebPlugins.MVCTemplate;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Root3/Index.cshtml")]
    public partial class _Views_Root3_Index_cshtml : System.Web.Mvc.WebViewPage<PluggedMVC.WebPlugins.MVCTemplate.Models.Root3Model>
    {
        public _Views_Root3_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\n\n<html>\n<head>\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\n    <title>Index</title>\n</head>\n\n<body>\n    <div> \n        <h1>This is Root3" +
" View from MVCTemplate Plugin.</h1>\n    </div>\n</body>\n</html>\n");

        }
    }
}
#pragma warning restore 1591
