#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using PluggedMVC.WebPlugins.MVCTemplate;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Root3/Index.cshtml")]
    public partial class _Views_Root3_Index_cshtml : System.Web.Mvc.WebViewPage<List<PluggedMVC.Core.Model.PersonViewModel>>
    {
        public _Views_Root3_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("    <h1>This is Root3 View from MVCTemplate Plugin.</h1>\r\n    <p>Following are li" +
"st of First Name of Person entity.</p>\r\n\r\n");

            
            #line 6 "..\..\Views\Root3\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Root3\Index.cshtml"
     foreach (var item in Model)
    {
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Root3\Index.cshtml"
   Write(Html.DisplayFor(m => item.FirstName));

            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Root3\Index.cshtml"
                                             

            
            #line default
            #line hidden
WriteLiteral("        <br />\r\n");

            
            #line 10 "..\..\Views\Root3\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
